---
- name: Ensure VSCode
  homebrew_cask:
    name: visual-studio-code
    state: present

- name: Install Visual Studio Code extensions
  command: code --install-extension {{ item.id | default(item) }}
  with_items: "{{ vsc_extensions }}"
  register: result
  changed_when: "'already installed' not in result.stdout"

- name: Ensure config files
  copy:
    src: "home/Library/Application Support/Code/User/{{ item }}"
    dest: "{{ ansible_env.HOME }}/Library/Application Support/Code/User/{{ item }}"
  with_items:
    - settings.json
    - keybindings.json
