---
- name: Ensure rbenv
  homebrew:
    name: rbenv
    state: present

- name: Check if ruby version is already installed
  shell: "rbenv versions | grep {{ ruby_version }}"
  register: ruby_installed
  changed_when: false
  ignore_errors: true

- name: Install ruby version
  shell: "rbenv install {{ ruby_version }}"
  when: ruby_installed.rc != 0

- name: Set global ruby version
  shell: "rbenv global {{ ruby_version }}"
  when: ruby_installed.rc != 0

- name: Ensure gems
  shell: gem install {{ item }}
  with_items:
    - rubocop
    - rubocop-daemon
    - solargraph
    - ruby-debug-ide
    - pry

- name: Ensure rubocop-daemon-wrapper dir
  file:
    path: /usr/local/bin/rubocop-daemon-wrapper
    state: directory

- name: Ensure robocop-daemon-wrapper
  get_url:
    url: https://raw.githubusercontent.com/fohte/rubocop-daemon/master/bin/rubocop-daemon-wrapper
    dest: /usr/local/bin/rubocop-daemon-wrapper/rubocop
    mode: +x

- name: Ensure custom pry
  copy:
    src: "home/.pryrc"
    dest: "{{ ansible_env.HOME }}/.pryrc"
